services:
  orch-node:
    image: gridlocknetwork/orch-node:latest
    container_name: orch-node
    ports:
      - "3000:3000"
    volumes:
      - ./example.env:/app/.env
    depends_on:
      mongodb:
        condition: service_healthy
      nats:
        condition: service_healthy
    networks:
      - gridlock-net

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - gridlock-net
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    command: ["--quiet", "--logpath=/dev/null", "--logappend"]
    logging:
      driver: "none"

  nats:
    image: nats:latest
    container_name: nats-main
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - gridlock-net
    healthcheck:
      test: ["CMD", "/nats-server", "--help"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  gridlock-net:
    name: gridlock-net
    external: true
    driver: bridge

volumes:
  mongodb_data: