services:
  gridlock-orch-stack:
    image: gridlocknetwork/orch-node:latest
    container_name: orch-node
    ports:
      - "5310:5310"
    volumes:
      - ./.env:/app/.env:ro
    env_file:
      - ./.env
    depends_on:
      mongodb:
        condition: service_healthy
      nats:
        condition: service_healthy
    networks:
      - gridlock-net

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      gridlock-net:
        aliases:
          - mongodb
    healthcheck:
      test: [ "CMD", "mongosh", "-u", "${MONGO_USERNAME}", "-p", "${MONGO_PASSWORD}", "--authenticationDatabase", "admin", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    command: [ "--quiet", "--logpath=/dev/null", "--logappend" ]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  nats:
    image: nats:latest
    container_name: nats-main
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - ./nats-server.conf:/etc/nats/nats-server.conf:ro
    command: [ "--config", "/etc/nats/nats-server.conf" ]
    networks:
      - gridlock-net
    healthcheck:
      test: [ "CMD", "/nats-server", "--help" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  gridlock-net:
    name: gridlock-net
    external: true
    driver: bridge

volumes:
  mongodb_data:
    name: orch-node-mongodb-data
